[package]
name = "mini-metars"
version = "0.0.6"
description = "A small on-top display for METARs"
authors = ["Ken Greim"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
tauri = { version = "2.5.1", features = ["default"] }
tauri-plugin-shell = "2.2.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
anyhow = "1.0.98"
flate2 = "1.1.1"
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1.44.2", features = ["macros"] }
chrono = { version = "0.4.41", features = ["serde"] }
vatsim_utils = "0.5.3"
regex = "1.11.1"
dirs = "6.0.0"
tauri-plugin-dialog = "2.2.1"
tauri-plugin-os = "2.2.1"
tauri-plugin-log = "2.4.0"
log = "0.4.27"
octocrab = "0.44.0"
semver = "1.0.26"
tokio-tungstenite = "0.26.2"
futures-util = "0.3.31"
parking_lot = { version = "0.12.3", features = ["deadlock_detection"] }

# Optimize for smaller binary size
[profile.release]
panic = "abort"   # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true        # Enables link to optimizations
opt-level = "s"   # Optimize for binary size
strip = true      # Remove debug symbols
